version: '3.8'
services:
  web:
    image: node:23
    working_dir: /app
    command: node src/web/app.js
    volumes:
      - ./:/app
    restart: unless-stopped
    ports: 
      - 80:3000
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongodb-data:/data/db

